group 'com.zendesk.zendesk_messaging_flutter'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://zendesk.jfrog.io/artifactory/repo'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10"
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'com.zendesk.zendesk_messaging_flutter'
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 21
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

repositories {
    google()
    mavenCentral()
    maven {
        url 'https://zendesk.jfrog.io/artifactory/repo'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10"
    implementation 'zendesk.messaging:messaging-android:2.38.+'
}
